name: yvonix grid
favicon: null
layout_spectrum: 0.8490086710080504
typography_spectrum: 0.9634950214531273
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.011235281126573682
  lightness: 0.4830134850926697
  saturation: 0.8933614746201783
  rhythmicContrast: 0.4347564075142145
purpose: []
